# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Foster On GitHub
email: hawk100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Site of a busy guy that likes to have a good time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colakatz.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  colakatz

# Build settings
markdown: kramdown

theme: jekyll-theme-architect